# -*- coding: utf-8 -*-
#############################################################################
# Copyright Vlad Popovici <popovici@bioxlab.org>
#
# Licensed under the MIT License. See LICENSE file in root folder.
#############################################################################

__author__ = "Vlad Popovici <popovici@bioxlab.org>"

"""WSI -> Zarr ingestion: bake a vendor slide file into the canonical
Zarr v3 (sharded) pyramid read by :class:`compass.core.ZarrRaster`.

This is the Zarr retargeting of the legacy ``wsi2hdf5``
(``compass.legacy.core``): same pyramid-generation algorithm — crop to ROI,
iterative downsample via pyvips through temporary on-disk .v images,
shard-by-shard copy into the destination arrays — with the write step
producing the layout of :func:`compass.core.zarr_raster.write_pyramid`
instead of HDF5 groups.

pyvips is imported lazily (inside the functions that need it) so the pure
planning helpers remain importable without libvips installed.
"""

import logging
import tempfile
from math import floor
from os import PathLike
from pathlib import Path

import zarr
from zarr.codecs import BloscCodec

from ..core.zarr_raster import FORMAT_VERSION

logger = logging.getLogger(__name__)


def resolve_crop(width: int, height: int,
                 roi: dict,
                 crop: tuple[int, int, int, int] | bool) -> tuple[int, int, int, int]:
    """Resolve the crop specification of :func:`wsi2zarr` to a concrete
    (x0, y0, width, height) region at level 0.

    Args:
        width, height: full extent of the slide at level 0.
        roi: the scanner's scan-region metadata ({'x0','y0','width','height'}
            or empty) as reported by :class:`compass.connector.wsi.WSI`.
        crop: False for the whole image; True to auto-crop to ``roi`` (if
            present); or an explicit (x0, y0, width, height), clamped to the
            image extent.
    """
    x0, y0, w, h = 0, 0, width, height
    if isinstance(crop, bool):
        if crop and len(roi) > 0:
            x0 = roi.get('x0', 0)
            y0 = roi.get('y0', 0)
            w = roi.get('width', width)
            h = roi.get('height', height)
    else:
        x0, y0, w, h = crop
        x0 = max(0, min(x0, width - 1))   # >= 0, < width
        y0 = max(0, min(y0, height - 1))  # >= 0, < height
        w = min(w, width - x0)
        h = min(h, height - y0)
    return x0, y0, w, h


def plan_levels(width: int, height: int,
                x0: int = 0, y0: int = 0,
                downscale_factor: int = 2,
                min_size: int = 256) -> list[dict]:
    """Plan the pyramid: per-level extents (and the level-0 crop origin
    scaled down alongside), largest first, stopping before either dimension
    would drop below ``min_size``.

    Returns a list of dicts with keys ``w``, ``h``, ``x0``, ``y0``.
    """
    levels = [{'w': width, 'h': height, 'x0': x0, 'y0': y0}]
    while True:
        w = int(floor(levels[-1]['w'] / downscale_factor))
        h = int(floor(levels[-1]['h'] / downscale_factor))
        cx0 = int(floor(levels[-1]['x0'] / downscale_factor))
        cy0 = int(floor(levels[-1]['y0'] / downscale_factor))
        if w < min_size or h < min_size:
            break
        levels.append({'w': w, 'h': h, 'x0': cx0, 'y0': cy0})
    return levels


##-
def wsi2zarr(
        wsi_path: str | Path | PathLike,
        dst_path: str | Path | PathLike,
        crop: tuple[int, int, int, int] | bool = False,
        downscale_factor: int = 2,
        min_size: int = 256,
        chunk_size: int = 512,
        shard_factor: int = 8,
        tmp_dir: str | Path | PathLike | None = None,
        overwrite: bool = False,
) -> None:
    """Convert a WSI file to the canonical pyramidal Zarr v3 (sharded)
    format. Highest resolution is level ``"0"``.

    The pyramid is rebuilt rather than copied from the WSI: level 0 is the
    (cropped) base image; every further level is generated by downscaling
    the previous one with pyvips. This gives control over the pyramid
    structure independently of what the scanner stored. Temporary .v images
    (uncompressed, together several times the size of level 0) keep RAM
    pressure low; data moves into Zarr one shard at a time, so peak memory
    of the copy step is a single shard regardless of slide size.

    :param wsi_path: source file path.
    :param dst_path: destination Zarr group (directory).
    :param crop: either bool to control auto-crop to the scan ROI, or
        (x0, y0, width, height) for an explicit crop region.
    :param downscale_factor: downsampling factor between pyramid levels.
    :param min_size: minimum size (either width or height) of the last level.
    :param chunk_size: chunk edge (pixels); match the viewer's tile size.
    :param shard_factor: shard edge, in chunks.
    :param tmp_dir: directory for the temporary .v images (default: next to
        ``dst_path``). Point it at a fast local disk when ``dst_path`` is on
        slow storage (USB/network drive): the intermediates are written and
        re-read several times, and a slow disk backs up the OS write cache
        until RAM runs out. Avoid a RAM-backed ``/tmp`` (tmpfs) — the
        intermediates are slide-sized.
    :param overwrite: overwrite an existing store at ``dst_path``.
    """
    import pyvips

    from .wsi import WSI

    wsi_path = Path(wsi_path)
    dst_path = Path(dst_path)
    dst_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_dir = dst_path.parent if tmp_dir is None else Path(tmp_dir)
    tmp_dir.mkdir(parents=True, exist_ok=True)

    wsi = WSI(wsi_path)
    x0, y0, width, height = resolve_crop(
        wsi.info["width"], wsi.info["height"], wsi.info["roi"], crop)
    levels = plan_levels(width, height, x0, y0, downscale_factor, min_size)
    nlevels = len(levels)

    logger.info("wsi2zarr: %d levels to generate (level 0 is just a copy)", nlevels)

    with tempfile.TemporaryDirectory(dir=tmp_dir) as tmp_path:
        tmp_path = Path(tmp_path)

        logger.info("wsi2zarr: copy base level, crop (%d, %d, %d, %d)",
                    levels[0]['x0'], levels[0]['y0'], levels[0]['w'], levels[0]['h'])
        im = pyvips.Image.new_from_file(str(wsi_path), level=0, autocrop=False)
        im = im.crop(levels[0]['x0'], levels[0]['y0'], levels[0]['w'], levels[0]['h'])
        im = im.flatten(background=wsi.info['background'])
        im.write_to_file(str(tmp_path / "level0.v"))

        for level in range(1, nlevels):
            logger.info("wsi2zarr: generating level %d...", level)
            im = pyvips.Image.new_from_file(str(tmp_path / f"level{level - 1}.v"))
            im_scaled = im.resize(1.0 / downscale_factor, gap=2.0)
            im_scaled.write_to_file(str(tmp_path / f"level{level}.v"))

        logger.info("wsi2zarr: from temporary to destination")
        root = zarr.create_group(str(dst_path), overwrite=overwrite)
        codec = BloscCodec(cname="zstd", clevel=3, shuffle="shuffle")

        for level in range(nlevels):
            logger.info("wsi2zarr: copying level %d...", level)
            im = pyvips.Image.new_from_file(str(tmp_path / f"level{level}.v"))
            ch, cw = im.height, im.width
            # chunks clipped to small levels; shards must stay a multiple
            # of them (as in write_pyramid)
            chy, chx = min(chunk_size, ch), min(chunk_size, cw)
            shy, shx = chy * shard_factor, chx * shard_factor
            arr = root.create_array(
                name=str(level),
                shape=(ch, cw, 3),  # YXC axes
                dtype="uint8",
                chunks=(chy, chx, 3),
                shards=(shy, shx, 3),
                compressors=codec,
            )
            # One whole shard per write: no read-modify-write of partial
            # shards, and memory bounded by the shard (not the slide) size.
            for j in range(0, ch, shy):
                bh = min(shy, ch - j)
                for i in range(0, cw, shx):
                    bw = min(shx, cw - i)
                    arr[j: j + bh, i: i + bw] = im.crop(i, j, bw, bh).numpy()

            # scale-specific metadata
            sf = downscale_factor ** level  # scale factor from level 0
            arr.attrs["mpp_x"] = sf * wsi.info['mpp_x']
            arr.attrs["mpp_y"] = sf * wsi.info['mpp_y']
            arr.attrs["objective_power"] = wsi.info['objective_power'] / sf
            arr.attrs["scale_factor"] = sf

        root.attrs["compass_version"] = FORMAT_VERSION
        root.attrs["level_count"] = nlevels
        root.attrs["base_mpp"] = 0.5 * (wsi.info["mpp_x"] + wsi.info["mpp_y"])
        root.attrs["base_mag_step"] = downscale_factor
        root.attrs["base_objective_power"] = wsi.info['objective_power']
        root.attrs["channel_names"] = ["R", "G", "B"]
        root.attrs["dimension_names"] = ["y", "x", "c"]

    logger.info("wsi2zarr: done")
##
